### ISSUE TITLE
[shop] PR err

### ISSUE THREAD

**Issue by Derekleeck** [reseltbitcamp/reselt#113]
오늘 자 업데이트 git bash로 push 해두었는데,  github상에서 PR 생성이 안됩니다..

new branch로 shop/script 생성되었는지 확인해주시면 감사하겠습니다.

브랜치 확인 안된다면 clone새로 하고 backup 덮어서 다시 PR 올리겠습니다
확인하시고 advise 해주세요

**Comment by HaGyeongEom** [comment]
![commit 오류](https://user-images.githubusercontent.com/100783823/178112360-26c50f32-daa1-4e3c-9c6c-48141450d271.JPG)

[shop/script] 해당 branch로 push된 마지막 커밋 메세지가 [수정: shopdetailpage revised]로 뜹니다.
이미 Merge되어있는 걸로 봐서 수정사항이 원격 저장소로 push가 안된 것 같네요.
새로 백업 후 pr 올려주시면 감사드리겠습니다!

**Comment by Derekleeck** [comment]
감사합니다!
