### ISSUE TITLE
[shop] toggle / style form 재작업 시작

### ISSUE THREAD

**Issue by Derekleeck** [reseltbitcamp/reselt#211]
ajax에 의해 toggle ID가 복수로 생성되었을 시, event가 발생하지 않는 에러가 있습니다. 
수정 경험 있으시면 공유 부탁 드립니다

**Comment by HaGyeongEom** [comment]
![image](https://user-images.githubusercontent.com/100783823/180370533-812bf061-c6a8-45e3-ac83-8170c9732725.png)
![image](https://user-images.githubusercontent.com/100783823/180370583-40444441-a0b8-4f21-b390-bc3977b44186.png)

id가 아니라 class를 이용하시거나
혹은 보내줄 값이 있으면, function을 새로 만들어서 이벤트 직접 걸어주셔도 돼요.
저 같은 경우에는 이런 식으로 값을 보내주고 함수를 호출했습니다.
