### ISSUE TITLE
menu.jsp - 센터에 breadcrumb 추가 건의

### ISSUE THREAD

**Issue by yeonsubak** [reseltbitcamp/reselt#46]
하기 이미지와 같이 menu.jsp 센터에 breadcrumb를 추가할까합니다.

![image](https://user-images.githubusercontent.com/91791222/177604464-2d209bac-0a05-4acc-a955-7f4dfbe146d6.png)
![image](https://user-images.githubusercontent.com/91791222/177604271-5ffde0df-6230-4639-adef-cafa1564e62a.png)

관련하여 의견 부탁드립니다.

**Comment by Derekleeck** [comment]
index 안에 menu.jsp로 include되는 것 맞나요
저는 동의

**Comment by HaGyeongEom** [comment]
상단에는 메인으로 돌아가는 로고 버튼, 네비게이션 등 페이지 이동되는 것들로 구성되어있어 그대로 두는 게 낫지 않을까요? 현재 페이지 표시는 네비게이션 js로 추후 구현될 예정이니까, 중복되는 것이 신경 쓰인다면 Shop 타이틀 부분을 제외하는 방향이 더 좋지 않을까 싶습니다. 의견 부탁드려요! @Derekleeck
